# Generated by Django 5.0.6 on 2024-07-07 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0002_alter_measurement_temperature"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sensors",
            new_name="Sensor",
        ),
    ]
