services:
  server_fastap:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
  db_fastapi:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - 5435:5432
    volumes:
      - postgres_data_fastapi:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin_fastapi:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8085:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data_fastapi: