# Generated by Django 5.0.6 on 2024-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
