services:
  db_flask:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - 5433:5432
    volumes:
      - postgres_data_flask:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  pgadmin_flask:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

volumes:
  postgres_data_flask: